version: 2.1
config: &config
  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx2G"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"


orbs:
  slack: circleci/slack@0.1.0
  android: circleci/android@0.2.1

jobs:
  build:
    <<: *config
    executor: android/android
    parameters:
      ndk-sha:
        default: 9c842cfaf44bae0ca17d7f6eac3f7e20864ce197
        description: >
          SHA-1 of the zip file specified by ndk-version. Provide a string formatted
          along the lines of the default value. See
          https://developer.android.com/ndk/downloads
        type: string
      ndk-version:
        default: android-ndk-r21c
        description: >
          Version of the NDK to install. Provide a string formatted along the lines
          of the default value.
        type: string
    steps:
      - checkout
      - run:
          name: "Cleaning Android"
          command: ./gradlew clean
      - run:
          name: "Building Android"
          command: ./gradlew assembleStageDebug --stacktrace
