name: Android CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew  --no-daemon clean bundleStage
    - name: Save Artifact
      uses: actions/upload-artifact@v1
      with:
        name: stage_bundle.aab
        path: "app/build/outputs/bundle/stageRelease/app-stage-release.aab"
  changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install
        env:
          GITHUB_AUTH: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          npx lerna-changelog
